export const GAME_CONFIG = {
  CANVAS_MAX_WIDTH: 800,
  CANVAS_MAX_WIDTH_PADDING: 40,
  CANVAS_MAX_HEIGHT: 500,
  CANVAS_MAX_HEIGHT_PADDING: 200,

  BALL_RADIUS: 22,
  BALL_START_X_RATIO: 0.15,
  BALL_START_Y_RATIO: 0.7,

  HOOP_X_RATIO: 0.78,
  HOOP_Y_RATIO: 0.32,
  HOOP_WIDTH: 55,
  HOOP_HEIGHT: 40,

  GRAVITY: 0.5,
  AIR_RESISTANCE: 0.995,

  POWER_SCALE: 0.15,
  POWER_MAX: 22,
  POWER_MIN_THRESHOLD: 2,

  DRAG_DISTANCE_THRESHOLD_MULTIPLIER: 3,

  FLOOR_HEIGHT: 40,
  FLOOR_BOUNCE_Y_DAMPING: -0.6,
  FLOOR_BOUNCE_X_DAMPING: 0.8,
  WALL_BOUNCE_DAMPING: -0.7,
  CEILING_BOUNCE_DAMPING: -0.7,
  REST_VY_THRESHOLD: 1.5,
  REST_VX_THRESHOLD: 1,

  PARTICLE_COUNT: 50,
  PARTICLE_VX_RANGE: 15,
  PARTICLE_VY_RANGE: 15,
  PARTICLE_VY_OFFSET: -5,
  PARTICLE_LIFE_BASE: 1,
  PARTICLE_LIFE_RANDOM: 0.5,
  PARTICLE_SIZE_BASE: 4,
  PARTICLE_SIZE_RANDOM: 4,
  PARTICLE_COLORS: ["#f97316", "#fbbf24", "#22c55e", "#3b82f6", "#ef4444"],
  PARTICLE_LIFE_DECAY: 0.025,
  PARTICLE_GRAVITY: 0.3,
  PARTICLE_FRICTION: 0.98,

  SCORE_TEXT_LIFE: 1.5,
  SCORE_TEXT_LIFE_DECAY: 0.02,
  SCORE_TEXT_RISE_SPEED: 1.5,
  SCORE_TEXT_OFFSET_Y: -20,
  SCORE_TEXT_BELOW_HOOP_Y: 20,

  FLASH_INTENSITY: 1,
  FLASH_DECAY_RATE: 0.08,
  FLASH_ALPHA_MULTIPLIER: 0.4,

  DELTA_TIME_DIVISOR: 16.67,
  DELTA_TIME_MAX: 2,

  SCORE_COOLDOWN_MS: 800,

  ANGULAR_VELOCITY_DECAY: 0.98,

  TRAJECTORY_DOTS: 25,
  TRAJECTORY_DOT_MIN_SIZE: 2,
  TRAJECTORY_DOT_START_SIZE: 5,
  TRAJECTORY_DOT_SIZE_DECAY: 0.15,

  POWER_BAR_WIDTH: 80,
  POWER_BAR_HEIGHT: 8,
  POWER_BAR_OFFSET_Y: 45,

  STREAK_SCORE_BASE: 10,

  RIM_COLLISION_BOUNCE: 1.5,
  RIM_COLLISION_DAMPING: 0.7,
  RIM_COLLISION_ANGULAR_FACTOR: 0.05,
  RIM_INWARD_OFFSET: 3,
  RIM_PASS_THROUGH_DEPTH: 30,

  BACKBOARD_BOUNCE_DAMPING: -0.6,
  BACKBOARD_ANGULAR_FACTOR: 0.03,

  HOOP_RIM_RADIUS: 8,
  HOOP_BACKBOARD_WIDTH: 10,
  HOOP_BACKBOARD_HEIGHT: 80,
  HOOP_NET_SEGMENTS: 6,
  HOOP_BACKBOARD_OFFSET_X: 15,
  HOOP_BACKBOARD_Y_OFFSET: 10,
  HOOP_TARGET_SQUARE_WIDTH: 32,
  HOOP_TARGET_SQUARE_HEIGHT: 28,
  HOOP_POLE_WIDTH: 6,
  HOOP_POLE_HEIGHT: 180,
  HOOP_POLE_Y_OFFSET: 15,
} as const;
